
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 108
#define YY_END_OF_BUFFER 109
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[310] =
    {   0,
        0,    0,  109,  107,  106,  106,   50,  107,  105,   47,
       45,  107,    9,    8,   42,   40,   37,   36,   33,   32,
      101,  101,   30,   29,   28,   24,   21,   10,    7,    6,
       15,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,    5,   13,    4,
        3,   49,    0,  104,  105,  105,  105,   46,   44,   43,
        0,  104,    0,   41,   39,   38,   35,    0,  101,  101,
       34,  100,    0,    1,   31,   98,    0,    0,    0,    0,
       27,   25,   23,   20,   19,   14,  105,  105,  105,  105,
      105,   60,  105,  105,  105,  105,  105,  105,  105,   68,

      105,   71,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,   12,   11,   48,    0,    0,    0,    0,    0,    1,
       98,   97,   99,   97,   26,   22,   18,   17,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,   66,  105,  105,  105,  105,   74,   75,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,   86,  105,  105,   88,  105,  105,  105,  105,    0,
        0,    0,    2,   16,  105,   52,  105,  105,  105,  105,
      105,  105,  105,   61,   62,  105,  105,  105,  105,  105,

      105,  105,  105,  105,   93,  105,  105,  105,  105,  105,
      105,  105,  105,   84,  105,   95,  105,  105,   89,  105,
       91,  105,    0,    0,  100,   51,   53,   54,   55,  105,
      105,  105,  105,  105,  105,   96,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,   82,  105,
       85,  105,  105,   90,   92,    0,  102,  105,  105,  105,
       59,   63,  105,  105,  105,  105,   70,  105,  105,  105,
      105,  105,   79,   80,   81,   83,   87,  105,    0,  105,
      105,   58,   64,   65,  105,  105,  105,  105,   76,   77,
      105,  105,  103,   56,   57,   67,  105,  105,  105,  105,

      105,  105,  105,   73,   78,   94,   69,   72,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,    1,   29,   29,   29,   29,   30,   29,
       31,   31,   31,   31,   31,   31,   31,   31,   32,   31,
       31,   31,   31,   31,   31,   31,   31,   33,   31,   31,
       34,   35,   36,   37,   38,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   31,   48,   49,   50,   51,
       52,   53,   31,   54,   55,   56,   57,   58,   59,   60,
       61,   31,   62,   63,   64,   65,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[66] =
    {   0,
        1,    2,    3,    1,    1,    1,    4,    1,    1,    1,
        5,    5,    1,    1,    1,    1,    1,    5,    6,    6,
        6,    6,    1,    1,    1,    1,    1,    1,    6,    6,
        7,    7,    7,    1,    5,    1,    1,    4,    6,    6,
        6,    6,    6,    6,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[317] =
    {   0,
        0,    0,  684,  685,  685,  685,  657,  676,   59,  655,
       58,   58,  685,  685,  654,   56,  685,   69,   52,   74,
       84,   90,  685,  685,   50,  653,   72,  685,  685,  685,
      652,  101,   76,   75,   83,   94,  106,   40,   88,  110,
       59,  109,  108,   84,  119,  128,   72,  685,   51,  685,
      685,  651,  670,  669,  620,    0,  619,  685,  685,  685,
      662,  685,  130,  685,  685,  685,  685,  157,  164,  172,
      685,  176,  658,    0,  685,  182,  188,    0,  133,  191,
      644,  685,  643,  685,  187,  685,  116,  161,  166,  167,
      182,  614,  169,  171,  176,  184,  183,  613,  188,  612,

      187,  189,  192,  193,  200,  209,  204,  213,  201,  220,
      207,  215,  217,  211,  222,  146,  611,  219,  223,  224,
      118,  685,  685,  685,  271,  297,  268,  651,  645,    0,
      266,    0,  269,    0,  685,  685,  685,  636,  240,  252,
      242,  243,  248,  251,  268,  266,  278,  274,  271,  288,
      275,  294,  607,  293,  297,  289,  301,  606,  605,  303,
      302,  300,  305,  311,  309,  308,  324,  314,  317,  321,
      326,  604,  331,  333,  603,  335,  330,  181,  332,  371,
      397,  375,  685,  685,  334,  602,  352,  348,  351,  374,
      354,  366,  368,  601,  600,  599,  378,  388,  355,  379,

      391,  598,  404,  597,  596,  405,  407,  406,  400,  595,
      401,  594,  409,  593,  371,  592,  399,  408,  591,  413,
      590,  415,  451,  633,  455,  588,  587,  586,  585,  414,
      433,  430,  442,  410,  444,  584,  434,  435,  447,  446,
      452,  455,  459,  451,  467,  469,  460,  471,  583,  470,
      582,  473,  468,  581,  580,  509,  685,  478,  483,  464,
      579,  578,  479,  482,  488,  501,  573,  500,  506,  503,
      504,  505,  568,  557,  556,  552,  546,  511,  589,  513,
      542,  541,  540,  539,  512,  517,  521,  528,  537,  535,
      527,  529,  685,  534,  465,  329,  520,  525,  530,  536,

      538,  531,  543,  299,  281,  245,  126,   42,  685,  597,
      601,  608,  610,  617,  624,   63
    } ;

static yyconst flex_int16_t yy_def[317] =
    {   0,
      309,    1,  309,  309,  309,  309,  309,  310,  311,  309,
      309,  312,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  311,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,  309,  309,  309,
      309,  309,  310,  309,   32,  313,   32,  309,  309,  309,
      312,  309,  312,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  314,  315,  309,  309,  309,  316,  309,  316,
      309,  309,  309,  309,  309,  309,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,

       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,  309,  309,  309,  312,  125,  309,  314,  309,  315,
      309,  316,  309,   80,  309,  309,  309,  309,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,  125,
      125,  309,  309,  309,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,

       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,  125,  312,  309,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,  125,  309,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,  312,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,  309,   32,   32,   32,   32,   32,   32,   32,

       32,   32,   32,   32,   32,   32,   32,   32,    0,  309,
      309,  309,  309,  309,  309,  309
    } ;

static yyconst flex_int16_t yy_nxt[751] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   23,   24,   25,   26,   27,   28,    9,    9,
        9,    9,    9,   29,    4,   30,   31,    9,    9,   32,
       33,   34,   35,   36,    9,    9,   37,    9,   38,    9,
       39,    9,   40,   41,   42,   43,   44,   45,   46,    9,
       47,   48,   49,   50,   51,   55,   59,   62,  132,   65,
       72,   72,   72,   72,   81,   82,  122,   56,   56,   56,
       56,   66,  103,   60,   67,   68,   73,   69,   70,   70,
       70,   74,   63,   57,   71,   57,   55,   84,   85,   75,

       68,  109,   76,   76,   76,   70,   68,   55,   70,   70,
       70,   70,   57,  123,   88,   77,   78,   91,  121,   56,
       56,   56,   56,   79,   89,   57,   92,   90,   57,   57,
      104,   93,   96,   94,  116,   77,   57,   57,   55,   62,
       97,   57,   95,   78,  105,   98,   80,   57,  106,  100,
       99,  133,  133,  113,   87,  101,  102,  117,  139,   57,
      179,  114,   57,  107,  110,  111,  108,  112,  115,   57,
      118,   57,   57,  119,  120,   72,   72,   72,   72,   57,
       68,   57,   76,   76,   76,   70,  125,  174,   68,  126,
       70,   70,   70,   70,   72,   72,   72,   72,   68,   57,

       76,   76,   76,   70,  142,  127,  131,  131,  131,  134,
      134,  134,  137,  138,   57,  140,  141,  143,  127,   57,
       57,  144,   57,  147,   57,  145,  221,  148,  149,   57,
      146,  150,  151,  152,   57,   57,   57,   57,  154,  155,
       57,   57,   57,  156,  157,   57,   57,  158,  160,  161,
      162,  159,  164,   57,   57,  163,  165,   57,  166,  167,
       57,  168,   57,  169,   57,  176,   57,  171,   57,  177,
      170,  172,   57,   57,  173,   57,   57,   57,  185,  178,
       62,  182,  187,  182,  131,  131,  131,  133,  133,  180,
      180,  180,  180,   57,  186,   57,   57,  188,   57,  180,

      180,   57,  189,  190,   57,   57,  192,  191,  193,  180,
      180,  180,  180,  180,  180,  181,  181,  181,  181,   57,
      194,   57,  196,  195,   57,  181,  181,   57,   57,  198,
      197,   57,  199,  200,   57,  181,  181,  181,  181,  181,
      181,   57,   57,  204,  203,  201,   57,   57,  202,  206,
       57,  205,   57,   57,   57,   57,   57,  207,   57,  209,
      208,   57,   57,  211,   57,  210,  212,   57,  216,  213,
       57,  214,  215,  217,   57,  218,  219,   57,  220,   57,
      222,  226,   57,   57,   57,   57,   57,   57,   57,  223,
      223,  223,  223,  225,  225,  225,  225,  227,  231,  223,

      223,   57,  228,  237,   57,   57,  229,   57,   57,  223,
      223,  223,  223,  223,  223,  224,  224,  224,  224,   57,
      230,   57,  232,  233,   57,  224,  224,   57,  235,  251,
      236,   57,   57,  239,  238,  224,  224,  224,  224,  224,
      224,   57,  241,  243,   57,  244,  246,  248,  245,  250,
      252,  253,   57,   57,   57,  254,  255,   57,   57,   57,
       57,   57,   57,   57,  258,  262,   57,   57,   57,  256,
      256,  256,  256,  225,  225,  225,  225,  259,  260,  256,
      256,  265,  264,   57,  261,  263,   57,   57,   57,  256,
      256,  256,  256,  256,  256,   57,  266,   57,  269,   57,

       57,  267,  268,  270,   57,   57,  271,  272,   57,  273,
      274,  275,   57,   57,  278,  276,  277,   57,   57,  282,
       57,   57,   57,   57,   57,  281,   57,  279,  279,  279,
      279,   57,   57,  283,  280,   57,   57,  279,  279,  285,
      287,   57,  284,  286,  288,  289,  290,  279,  279,  279,
      279,  279,  279,   57,   57,  294,   57,   57,   57,   57,
      291,  292,  296,  298,   57,   57,   57,  297,  299,  300,
       57,  301,  304,   57,   57,  302,  303,  305,   57,  306,
       57,   57,   57,   57,   57,  307,  308,   57,   57,   57,
       57,   57,   57,   57,   57,  295,   57,   53,  293,   57,

       53,   53,   53,   53,   57,   57,   57,   57,   61,   57,
       57,   61,   61,   61,   61,   56,   56,  128,  128,  128,
      128,   57,  128,  128,  130,  130,   57,  130,  130,  130,
      130,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,  257,   57,   57,   57,   57,  249,  247,   57,
      242,  240,  234,   57,   57,   57,   57,   57,   57,   57,
       57,  184,  183,  129,  175,   57,  153,   57,  136,  135,
      129,   62,   57,   57,   54,   54,  124,   86,   83,   64,
       58,   54,   52,  309,    3,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,

      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309
    } ;

static yyconst flex_int16_t yy_chk[751] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    9,   11,   12,  316,   16,
       19,   19,   19,   19,   25,   25,   49,    9,    9,    9,
        9,   16,   38,   11,   18,   18,   20,   18,   18,   18,
       18,   20,   12,   38,   18,  308,    9,   27,   27,   20,

       21,   41,   21,   21,   21,   21,   22,   32,   22,   22,
       22,   22,   41,   49,   33,   21,   21,   34,   47,   32,
       32,   32,   32,   21,   33,   47,   34,   33,   34,   33,
       39,   35,   36,   35,   44,   21,   35,   44,   32,   63,
       36,   39,   35,   21,   39,   36,   21,   36,   40,   37,
       36,   79,   79,   43,   32,   37,   37,   45,   87,   37,
      121,   43,   42,   40,   42,   42,   40,   42,   43,   87,
       45,  121,   45,   46,   46,   68,   68,   68,   68,  307,
       69,   46,   69,   69,   69,   69,   63,  116,   70,   63,
       70,   70,   70,   70,   72,   72,   72,   72,   76,  116,

       76,   76,   76,   76,   89,   72,   77,   77,   77,   80,
       80,   80,   85,   85,   88,   88,   88,   90,   72,   89,
       90,   91,   93,   93,   94,   91,  178,   94,   95,   95,
       91,   95,   96,   97,  178,   91,   97,   96,   99,  101,
      101,   99,  102,  102,  102,  103,  104,  103,  105,  106,
      107,  104,  108,  105,  109,  107,  109,  107,  110,  111,
      111,  112,  106,  113,  114,  118,  108,  114,  112,  119,
      113,  114,  118,  110,  115,  115,  119,  120,  139,  120,
      125,  127,  141,  127,  131,  131,  131,  133,  133,  125,
      125,  125,  125,  139,  140,  141,  142,  142,  306,  125,

      125,  143,  143,  143,  144,  140,  145,  144,  146,  125,
      125,  125,  125,  125,  125,  126,  126,  126,  126,  146,
      147,  145,  149,  148,  149,  126,  126,  148,  151,  151,
      150,  147,  152,  154,  305,  126,  126,  126,  126,  126,
      126,  150,  156,  157,  156,  155,  154,  152,  155,  161,
      155,  160,  304,  162,  157,  161,  160,  162,  163,  164,
      163,  166,  165,  166,  164,  165,  167,  168,  171,  168,
      169,  169,  170,  173,  170,  174,  176,  167,  177,  171,
      179,  185,  296,  177,  173,  179,  174,  185,  176,  180,
      180,  180,  180,  182,  182,  182,  182,  187,  191,  180,

      180,  188,  188,  199,  189,  187,  189,  191,  199,  180,
      180,  180,  180,  180,  180,  181,  181,  181,  181,  192,
      190,  193,  192,  193,  215,  181,  181,  190,  197,  215,
      198,  197,  200,  201,  200,  181,  181,  181,  181,  181,
      181,  198,  203,  206,  201,  207,  209,  211,  208,  213,
      217,  218,  217,  209,  211,  220,  222,  203,  206,  208,
      207,  218,  213,  234,  230,  234,  220,  230,  222,  223,
      223,  223,  223,  225,  225,  225,  225,  231,  232,  223,
      223,  238,  237,  232,  233,  235,  231,  237,  238,  223,
      223,  223,  223,  223,  223,  233,  239,  235,  242,  240,

      239,  240,  241,  243,  244,  241,  244,  245,  242,  246,
      247,  248,  243,  247,  253,  250,  252,  260,  295,  260,
      245,  253,  246,  250,  248,  259,  252,  256,  256,  256,
      256,  258,  263,  263,  258,  264,  259,  256,  256,  265,
      268,  265,  264,  266,  269,  270,  271,  256,  256,  256,
      256,  256,  256,  268,  266,  280,  270,  271,  272,  269,
      272,  278,  285,  287,  278,  285,  280,  286,  288,  291,
      286,  292,  299,  297,  287,  297,  298,  300,  298,  301,
      291,  288,  292,  299,  302,  302,  303,  294,  290,  300,
      289,  301,  284,  283,  282,  281,  303,  310,  279,  277,

      310,  310,  310,  310,  311,  276,  311,  311,  312,  275,
      274,  312,  312,  312,  312,  313,  313,  314,  314,  314,
      314,  273,  314,  314,  315,  315,  267,  315,  315,  315,
      315,  262,  261,  255,  254,  251,  249,  236,  229,  228,
      227,  226,  224,  221,  219,  216,  214,  212,  210,  205,
      204,  202,  196,  195,  194,  186,  175,  172,  159,  158,
      153,  138,  129,  128,  117,  100,   98,   92,   83,   81,
       73,   61,   57,   55,   54,   53,   52,   31,   26,   15,
       10,    8,    7,    3,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,

      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
#include "lexer.tab.hpp"
#include <iostream>
using namespace std;
#define YY_DECL extern "C" int yylex()
#line 727 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 10 "lexer.l"


#line 912 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 310 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 685 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 12 "lexer.l"
{ cout << "Found <L_COMMENT>: " << yytext << endl; return L_COMMENT; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 13 "lexer.l"
{ cout << "Found <B_COMMENT>: " << yytext << endl; return B_COMMENT; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 14 "lexer.l"
{ cout << "Found <BIT_NOT>:" <<  yytext << endl; return BIT_NOT; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 15 "lexer.l"
{ cout << "Found <CLOSE_C>: " << yytext << endl; return CLOSE_C; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 16 "lexer.l"
{ cout << "Found <OPEN_C>: " <<  yytext << endl; return OPEN_C; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 17 "lexer.l"
{ cout << "Found <CLOSE_B>:" << yytext << endl; return CLOSE_B; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 18 "lexer.l"
{ cout << "Found <OPEN_B>: " <<  yytext << endl; return OPEN_B; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 19 "lexer.l"
{ cout << "Found <CLOSE_P>: " << yytext << endl; return CLOSE_P; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 20 "lexer.l"
{ cout << "Found <OPEN_P>: " <<  yytext << endl; return OPEN_P; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 21 "lexer.l"
{ cout << "Found <TERNARY_OP>: " <<  yytext << endl; return TERNARY_OP; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 22 "lexer.l"
{ cout << "Found <LOGIC_OR_OP>: " <<  yytext << endl; return LOGIC_OR_OP; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 23 "lexer.l"
{ cout << "Found <SHORT_BIT_OR_OP>: " <<  yytext << endl; return SHORT_BIT_OR_OP; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 24 "lexer.l"
{ cout << "Found <BIT_OR_OP>: " <<  yytext << endl; return BIT_OR_OP; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 25 "lexer.l"
{ cout << "Found <SHORT_BIT_XOR_OP>: " <<  yytext << endl; return SHORT_BIT_XOR_OP; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 26 "lexer.l"
{ cout << "Found <BIT_XOR_OP>: " <<  yytext << endl; return BIT_XOR_OP; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 27 "lexer.l"
{ cout << "Found <SHORT_BIT_SHIFT_Z_R_OP>: " <<  yytext << endl; return SHORT_BIT_SHIFT_Z_R_OP; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 28 "lexer.l"
{ cout << "Found <BIT_SHIFT_Z_R_OP>: " <<  yytext << endl; return BIT_SHIFT_Z_R_OP; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 29 "lexer.l"
{ cout << "Found <SHORT_BIT_SHIFT_S_R_OP>: " <<  yytext << endl; return SHORT_BIT_SHIFT_S_R_OP; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 30 "lexer.l"
{ cout << "Found <BIT_SHIFT_S_R_OP>: " <<  yytext << endl; return BIT_SHIFT_S_R_OP; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 31 "lexer.l"
{ cout << "Found <GE_OP>: " <<  yytext << endl; return GE_OP; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 32 "lexer.l"
{ cout << "Found <G_OP>: " <<  yytext << endl; return G_OP; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 33 "lexer.l"
{ cout << "Found <EQ_VT_OP>: " <<  yytext << endl; return EQ_VT_OP; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 34 "lexer.l"
{ cout << "Found <EQ_V_OP>: " <<  yytext << endl; return EQ_V_OP; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 35 "lexer.l"
{ cout << "Found <VA_OP>: " <<  yytext << endl; return VA_OP; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 36 "lexer.l"
{ cout << "Found <LE_OP>: " <<  yytext << endl; return LE_OP; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 37 "lexer.l"
{ cout << "Found <SHORT_BIT_SHIFT_L_OP>: " <<  yytext << endl; return SHORT_BIT_SHIFT_L_OP; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 38 "lexer.l"
{ cout << "Found <BIT_SHIFT_L_OP>: " <<  yytext << endl; return BIT_SHIFT_L_OP; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 39 "lexer.l"
{ cout << "Found <L_OP>: " <<  yytext << endl; return L_OP; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 40 "lexer.l"
{ cout << "Found <STMT_TER_OP>: " <<  yytext << endl; return STMT_TER_OP; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 41 "lexer.l"
{ cout << "Found <PA_OP>: " <<  yytext << endl; return PA_OP; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 42 "lexer.l"
{ cout << "Found <SHORT_DIV_OP>: " <<  yytext << endl; return SHORT_DIV_OP; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 43 "lexer.l"
{ cout << "Found <DIV_OP>: " <<  yytext << endl; return DIV_OP; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 44 "lexer.l"
{ cout << "Found <MEM_ACC_OP>: " <<  yytext << endl; return MEM_ACC_OP; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 45 "lexer.l"
{ cout << "Found <SHORT_SUB_OP>: " <<  yytext << endl; return SHORT_SUB_OP; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 46 "lexer.l"
{ cout << "Found <UNIT_SUB_OP>: " <<  yytext << endl; return UNIT_SUB_OP; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 47 "lexer.l"
{ cout << "Found <SUB_OP>: " <<  yytext << endl; return SUB_OP; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 48 "lexer.l"
{ cout << "Found <SEP_OP>:" << yytext << endl; return SEP_OP; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 49 "lexer.l"
{ cout << "Found <SHORT_ADD_OP>: " <<  yytext << endl; return SHORT_ADD_OP; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 50 "lexer.l"
{ cout << "Found <UNIT_ADD_OP>: " <<  yytext << endl; return UNIT_ADD_OP; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 51 "lexer.l"
{ cout << "Found <ADD_OP>: " <<  yytext << endl; return ADD_OP; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 52 "lexer.l"
{ cout << "Found <SHORT_MUL_OP>: " <<  yytext << endl; return SHORT_MUL_OP; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 53 "lexer.l"
{ cout << "Found <MUL_OP>: " <<  yytext << endl; return MUL_OP; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 54 "lexer.l"
{ cout << "Found <SHORT_BIT_AND_OP>: " <<  yytext << endl; return SHORT_BIT_AND_OP; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 55 "lexer.l"
{ cout << "Found <LOGIC_AND_OP>: " <<  yytext << endl; return LOGIC_AND_OP; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 56 "lexer.l"
{ cout << "Found <BIT_AND_OP>: " <<  yytext << endl; return BIT_AND_OP; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 57 "lexer.l"
{ cout << "Found <SHORT_MOD_OP>: " <<  yytext << endl; return SHORT_MOD_OP; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 58 "lexer.l"
{ cout << "Found <MOD_OP>: " <<  yytext << endl; return MOD_OP; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 59 "lexer.l"
{ cout << "Found <NEG_VT_OP>: " <<  yytext << endl; return NEG_VT_OP; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 60 "lexer.l"
{ cout << "Found <NEG_V_OP>: " <<  yytext << endl; return NEG_V_OP; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 61 "lexer.l"
{ cout << "Found <LOGIC_NOT_OP>: " <<  yytext << endl; return LOGIC_NOT_OP; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 62 "lexer.l"
{ cout << "Found <BREAK>: " << yytext << endl; return BREAK; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 63 "lexer.l"
{ cout << "Found <CASE>: " << yytext << endl; return CASE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 64 "lexer.l"
{ cout << "Found <CATCH>: " << yytext << endl; return CATCH; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 65 "lexer.l"
{ cout << "Found <CLASS>: " << yytext << endl; return CLASS; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 66 "lexer.l"
{ cout << "Found <CONS>: " << yytext << endl; return CONS; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 67 "lexer.l"
{ cout << "Found <CONTINUE>: " << yytext << endl; return CONTINUE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 68 "lexer.l"
{ cout << "Found <DEBUGGER>: " << yytext << endl; return DEBUGGER; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 69 "lexer.l"
{ cout << "Found <DEFAULT>: " << yytext << endl; return DEFAULT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 70 "lexer.l"
{ cout << "Found <DELETE>: " << yytext << endl; return DELETE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 71 "lexer.l"
{ cout << "Found <DO>: " << yytext << endl; return DO; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 72 "lexer.l"
{ cout << "Found <ELSE>: " << yytext << endl; return ELSE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 73 "lexer.l"
{ cout << "Found <ENUM>: " << yytext << endl; return ENUM; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 74 "lexer.l"
{ cout << "Found <EXPORT>: " << yytext << endl; return EXPORT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 75 "lexer.l"
{ cout << "Found <EXTENDS>: " << yytext << endl; return EXTENDS; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 76 "lexer.l"
{ cout << "Found <FINALLY>: " << yytext << endl; return FINALLY; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 77 "lexer.l"
{ cout << "Found <FOR>: " << yytext << endl; return FOR; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 78 "lexer.l"
{ cout << "Found <FUNCTION>: " << yytext << endl; return FUNCTION; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 79 "lexer.l"
{ cout << "Found <IF>: " << yytext << endl; return IF; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 80 "lexer.l"
{ cout << "Found <IMPLEMENTS>: " << yytext << endl; return IMPLEMENTS; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 81 "lexer.l"
{ cout << "Found <IMPORT>: " << yytext << endl; return IMPORT; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 82 "lexer.l"
{ cout << "Found <IN>: " << yytext << endl; return IN; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 83 "lexer.l"
{ cout << "Found <INSTANCEOF>: " << yytext << endl; return INSTANCEOF; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 84 "lexer.l"
{ cout << "Found <INTERFACE>: " << yytext << endl; return INTERFACE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 85 "lexer.l"
{ cout << "Found <LET>: " << yytext << endl; return LET; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 86 "lexer.l"
{ cout << "Found <NEW>: " << yytext << endl; return NEW; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 87 "lexer.l"
{ cout << "Found <PACKAGE>: " << yytext << endl; return PACKAGE; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 88 "lexer.l"
{ cout << "Found <PRIVATE>: " << yytext << endl; return PRIVATE; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 89 "lexer.l"
{ cout << "Found <PROTECTED>: " << yytext << endl; return PROTECTED; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 90 "lexer.l"
{ cout << "Found <PUBLIC>: " << yytext << endl; return PUBLIC; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 91 "lexer.l"
{ cout << "Found <RETURN>: " << yytext << endl; return RETURN; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 92 "lexer.l"
{ cout << "Found <STATIC>: " << yytext << endl; return STATIC; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 93 "lexer.l"
{ cout << "Found <SUPER>: " << yytext << endl; return SUPER; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 94 "lexer.l"
{ cout << "Found <SWITCH>: " << yytext << endl; return SWITCH; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 95 "lexer.l"
{ cout << "Found <THIS>: " << yytext << endl; return THIS; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 96 "lexer.l"
{ cout << "Found <THROW>: " << yytext << endl; return THROW; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 97 "lexer.l"
{ cout << "Found <TRY>: " << yytext << endl; return TRY; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 98 "lexer.l"
{ cout << "Found <TYPEOF>: " << yytext << endl; return TYPEOF; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 99 "lexer.l"
{ cout << "Found <VAR>: " << yytext << endl; return VAR; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 100 "lexer.l"
{ cout << "Found <VOID>: " << yytext << endl; return VOID; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 101 "lexer.l"
{ cout << "Found <WHILE>: " << yytext << endl; return WHILE; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 102 "lexer.l"
{ cout << "Found <WITH>: " << yytext << endl; return WITH; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 103 "lexer.l"
{ cout << "Found <YIELD>: " << yytext << endl; return YIELD; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 104 "lexer.l"
{ cout << "Found <NULL_V>: " << yytext << endl; return NULL_V; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 105 "lexer.l"
{ cout << "Found <UNDEFINED_V>: " << yytext << endl; return UNDEFINED_V; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 106 "lexer.l"
{ cout << "Found <TRUE_V>: " << yytext << endl; return TRUE_V; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 107 "lexer.l"
{ cout << "Found <FALSE_V>: " << yytext << endl; return FALSE_V; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 108 "lexer.l"
{ cout << "Found <HEX_T>: " << yytext << endl; return HEX_T; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 109 "lexer.l"
{ cout << "Found <OCT_T>: " << yytext << endl; return OCT_T; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 110 "lexer.l"
{ cout << "Found <BIN_T>: " << yytext << endl; return BIN_T; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 111 "lexer.l"
{ cout << "Found <FLT_T>: " << yytext << endl; return FLT_T; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 112 "lexer.l"
{ cout << "Found <INT_T>: " << yytext << endl; return INT_T; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 113 "lexer.l"
{ cout << "Found <HEX_SEQ>: " << yytext << endl; return HEX_SEQ; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 114 "lexer.l"
{ cout << "Found <UNI_SEQ>: " << yytext << endl; return UNI_SEQ; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 115 "lexer.l"
{ cout << "Found <STRING>: " << yytext << endl; return STRING; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 116 "lexer.l"
{ cout << "Found <ID>: " << yytext << endl; return ID; }
	YY_BREAK
case 106:
/* rule 106 can match eol */
YY_RULE_SETUP
#line 117 "lexer.l"
{ ; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 118 "lexer.l"
{ cout << "Error -> " << yytext << endl; exit(1); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 120 "lexer.l"
ECHO;
	YY_BREAK
#line 1537 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 310 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 310 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 309);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 120 "lexer.l"



int main()
{
  yylex();
}
